#!/usr/bin/env bash

tags="--git-dir=$DOTFILES/.git --work-tree=$DOTFILES"

pushd .
cd $DOTFILES

env -i git add .
env -i git diff .

# If no arg provided, the prompt for one
if [ -z "$1" ]
then
  read -p "Commit message: " commitMessage
else
  commitMessage=$1
fi

#env -i git $tags commit -am $commitMessage

popd
