#!/bin/bash
############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables
if [ -z "$1" ]
  then
    echo "ERROR_USAGE: No system root path supplied as argument"
    exit 128
  else
    root=$1
fi
dir=$root/.everc/dotfiles                    # dotfiles directory
olddir=$root/.everc/dotfiles_old             # old dotfiles backup directory
files="profile vimrc bashrc tmux.conf"    # list of files/folders to symlink in homedir

##########

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p $olddir
echo "...done"

# change to the dotfiles directory
echo "Changing to the $dir directory"
cd $dir
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
for file in $files; do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv $root/.$file $olddir
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file $root/.$file
done
